import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "../globals.css"
import React from "react"
import { TopBar } from "@/components/shared/TopBar"
import { LeftSidebar } from "@/components/shared/LeftSidebar"
import { Bottombar } from "@/components/shared/Bottombar"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-background-primary text-white`}>
        <TopBar />
        <main className="flex flex-row">
          <LeftSidebar />
          <section className="main-container">
            <div className="p-5 wrapper"> {children}</div>
          </section>
        </main>
        <Bottombar />
      </body>
    </html>
  )
}
